# Generated by Django 5.2.5 on 2026-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_participant_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['clicker_id']},
        ),
        migrations.AddField(
            model_name='question',
            name='option_display',
            field=models.CharField(choices=[('alpha', 'A, B, C, D...'), ('numeric', '1, 2, 3, 4...')], default='alpha', help_text='How to label options: A,B,C or 1,2,3', max_length=10),
        ),
    ]
