# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_participant_created_by_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL to display with the question', max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL (YouTube, Vimeo, or direct video link)', max_length=2000),
        ),
    ]
