# Generated by Django 5.2.5 on 2026-03-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_question_image_url_question_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_live_response',
            field=models.BooleanField(default=False, help_text='If true, show live response/option selection while participants are answering.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_response_after_completion',
            field=models.BooleanField(default=True, help_text='If true, show full responses/options after all participants complete.'),
        ),
    ]
