# Generated by Django 5.2.5 on 2026-03-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_exam_show_live_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_change_automatic',
            field=models.BooleanField(default=False, help_text='If true, questions auto-advance during live exam. If false, question change is manual.'),
        ),
    ]
