# Generated by Django 5.2.5 on 2026-03-24 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_participant_clicker_per_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('present', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance_records', to='api.participant')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_daily_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'participant_id'],
                'indexes': [models.Index(fields=['date', 'participant'], name='api_dailyat_date_4db9dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'date'), name='uniq_daily_attendance_participant_date')],
            },
        ),
    ]
